/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace Thrift.Test
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class VersioningTestV1 : TBase
  {
    private int _begin_in_both;
    private string _old_string;
    private int _end_in_both;

    public int Begin_in_both
    {
      get
      {
        return _begin_in_both;
      }
      set
      {
        __isset.begin_in_both = true;
        this._begin_in_both = value;
      }
    }

    public string Old_string
    {
      get
      {
        return _old_string;
      }
      set
      {
        __isset.old_string = true;
        this._old_string = value;
      }
    }

    public int End_in_both
    {
      get
      {
        return _end_in_both;
      }
      set
      {
        __isset.end_in_both = true;
        this._end_in_both = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool begin_in_both;
      public bool old_string;
      public bool end_in_both;
    }

    public VersioningTestV1() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.I32) {
              Begin_in_both = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 3:
            if (field.Type == TType.String) {
              Old_string = iprot.ReadString();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 12:
            if (field.Type == TType.I32) {
              End_in_both = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("VersioningTestV1");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (__isset.begin_in_both) {
        field.Name = "begin_in_both";
        field.Type = TType.I32;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(Begin_in_both);
        oprot.WriteFieldEnd();
      }
      if (Old_string != null && __isset.old_string) {
        field.Name = "old_string";
        field.Type = TType.String;
        field.ID = 3;
        oprot.WriteFieldBegin(field);
        oprot.WriteString(Old_string);
        oprot.WriteFieldEnd();
      }
      if (__isset.end_in_both) {
        field.Name = "end_in_both";
        field.Type = TType.I32;
        field.ID = 12;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(End_in_both);
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder __sb = new StringBuilder("VersioningTestV1(");
      bool __first = true;
      if (__isset.begin_in_both) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("Begin_in_both: ");
        __sb.Append(Begin_in_both);
      }
      if (Old_string != null && __isset.old_string) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("Old_string: ");
        __sb.Append(Old_string);
      }
      if (__isset.end_in_both) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("End_in_both: ");
        __sb.Append(End_in_both);
      }
      __sb.Append(")");
      return __sb.ToString();
    }

  }

}
