/* confdefs.h */
#define PACKAGE_NAME "thrift"
#define PACKAGE_TARNAME "thrift"
#define PACKAGE_VERSION "0.19.0"
#define PACKAGE_STRING "thrift 0.19.0"
#define PACKAGE_BUGREPORT ""
#define PACKAGE_URL ""
#define PACKAGE "thrift"
#define VERSION "0.19.0"
#define HAVE_STDIO_H 1
#define HAVE_STDLIB_H 1
#define HAVE_STRING_H 1
#define HAVE_INTTYPES_H 1
#define HAVE_STDINT_H 1
#define HAVE_STRINGS_H 1
#define HAVE_SYS_STAT_H 1
#define HAVE_SYS_TYPES_H 1
#define HAVE_UNISTD_H 1
#define STDC_HEADERS 1
#define HAVE_DLFCN_H 1
#define LT_OBJDIR ".libs/"
#define BISON_VERSION 0.0
#define BISON_VERSION 3.8.2
#define AUTOMAKE_VERSION 1.16.5
#define YYTEXT_POINTER 1
#define HAVE_CXX11 1
#define HAVE_ZLIB /**/
#define HAVE_STDBOOL_H 1
