/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
package com.facebook.thrift.reflection.limited;

import java.util.ArrayList;
import java.util.AbstractMap;
import java.util.HashMap;
import java.util.HashSet;
import com.facebook.thrift.*;

import com.facebook.thrift.protocol.*;
import com.facebook.thrift.transport.*;

public class SimpleType implements java.io.Serializable {
  public int ttype;
  public String name;

  public final Isset __isset = new Isset();
  public static final class Isset {
    public boolean ttype = false;
    public boolean name = false;
  }

  public SimpleType() {
  }

  public SimpleType(
    int ttype,
    String name)
  {
    this();
    this.ttype = ttype;
    this.__isset.ttype = true;
    this.name = name;
    this.__isset.name = true;
  }

  public void read(TProtocol iprot) throws TException {
    TField field;
    iprot.readStructBegin();
    while (true)
    {
      field = iprot.readFieldBegin();
      if (field.type == TType.STOP) { 
        break;
      }
      switch (field.id)
      {
        case 1:
          if (field.type == TType.I32) {
            this.ttype = iprot.readI32();
            this.__isset.ttype = true;
          } else { 
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case 2:
          if (field.type == TType.STRING) {
            this.name = iprot.readString();
            this.__isset.name = true;
          } else { 
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        default:
          TProtocolUtil.skip(iprot, field.type);
          break;
      }
      iprot.readFieldEnd();
    }
    iprot.readStructEnd();
  }

  public void write(TProtocol oprot) throws TException {
    TStruct struct = new TStruct("SimpleType");
    oprot.writeStructBegin(struct);
    TField field = new TField();
    field.name = "ttype";
    field.type = TType.I32;
    field.id = 1;
    oprot.writeFieldBegin(field);
    oprot.writeI32(this.ttype);
    oprot.writeFieldEnd();
    if (this.name != null) {
      field.name = "name";
      field.type = TType.STRING;
      field.id = 2;
      oprot.writeFieldBegin(field);
      oprot.writeString(this.name);
      oprot.writeFieldEnd();
    }
    oprot.writeFieldStop();
    oprot.writeStructEnd();
  }

  public String toString() {
    StringBuilder sb = new StringBuilder("SimpleType(");
    sb.append("ttype:");
    sb.append(this.ttype);
    sb.append(",name:");
    sb.append(this.name);
    sb.append(")");
    return sb.toString();
  }

}

