/**
 * Autogenerated by Thrift Compiler (@PACKAGE_VERSION@)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Threading;
using System.Threading.Tasks;
using Thrift;
using Thrift.Collections;

using Thrift.Protocols;
using Thrift.Protocols.Entities;
using Thrift.Protocols.Utilities;
using Thrift.Transports;
using Thrift.Transports.Client;
using Thrift.Transports.Server;


namespace thrift.test
{

    public partial class ListTypeVersioningV2 : TBase
    {
        private List<string> _strings;
        private string _hello;

        public List<string> Strings
        {
            get
            {
                return _strings;
            }
            set
            {
                __isset.strings = true;
                this._strings = value;
            }
        }

        public string Hello
        {
            get
            {
                return _hello;
            }
            set
            {
                __isset.hello = true;
                this._hello = value;
            }
        }


        public Isset __isset;
        public struct Isset
        {
            public bool strings;
            public bool hello;
        }

        public ListTypeVersioningV2()
        {
        }

        public async Task ReadAsync(TProtocol iprot, CancellationToken cancellationToken)
        {
            iprot.IncrementRecursionDepth();
            try
            {
                TField field;
                await iprot.ReadStructBeginAsync(cancellationToken);
                while (true)
                {
                    field = await iprot.ReadFieldBeginAsync(cancellationToken);
                    if (field.Type == TType.Stop)
                    {
                        break;
                    }

                    switch (field.ID)
                    {
                        case 1:
                            if (field.Type == TType.List)
                            {
                                {
                                    Strings = new List<string>();
                                    TList _list61 = await iprot.ReadListBeginAsync(cancellationToken);
                                    for(int _i62 = 0; _i62 < _list61.Count; ++_i62)
                                    {
                                        string _elem63;
                                        _elem63 = await iprot.ReadStringAsync(cancellationToken);
                                        Strings.Add(_elem63);
                                    }
                                    await iprot.ReadListEndAsync(cancellationToken);
                                }
                            }
                            else
                            {
                                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
                            }
                            break;
                        case 2:
                            if (field.Type == TType.String)
                            {
                                Hello = await iprot.ReadStringAsync(cancellationToken);
                            }
                            else
                            {
                                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
                            }
                            break;
                        default: 
                            await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
                            break;
                    }

                    await iprot.ReadFieldEndAsync(cancellationToken);
                }

                await iprot.ReadStructEndAsync(cancellationToken);
            }
            finally
            {
                iprot.DecrementRecursionDepth();
            }
        }

        public async Task WriteAsync(TProtocol oprot, CancellationToken cancellationToken)
        {
            oprot.IncrementRecursionDepth();
            try
            {
                var struc = new TStruct("ListTypeVersioningV2");
                await oprot.WriteStructBeginAsync(struc, cancellationToken);
                var field = new TField();
                if (Strings != null && __isset.strings)
                {
                    field.Name = "strings";
                    field.Type = TType.List;
                    field.ID = 1;
                    await oprot.WriteFieldBeginAsync(field, cancellationToken);
                    {
                        await oprot.WriteListBeginAsync(new TList(TType.String, Strings.Count), cancellationToken);
                        foreach (string _iter64 in Strings)
                        {
                            await oprot.WriteStringAsync(_iter64, cancellationToken);
                        }
                        await oprot.WriteListEndAsync(cancellationToken);
                    }
                    await oprot.WriteFieldEndAsync(cancellationToken);
                }
                if (Hello != null && __isset.hello)
                {
                    field.Name = "hello";
                    field.Type = TType.String;
                    field.ID = 2;
                    await oprot.WriteFieldBeginAsync(field, cancellationToken);
                    await oprot.WriteStringAsync(Hello, cancellationToken);
                    await oprot.WriteFieldEndAsync(cancellationToken);
                }
                await oprot.WriteFieldStopAsync(cancellationToken);
                await oprot.WriteStructEndAsync(cancellationToken);
            }
            finally
            {
                oprot.DecrementRecursionDepth();
            }
        }

        public override string ToString()
        {
            var sb = new StringBuilder("ListTypeVersioningV2(");
            bool __first = true;
            if (Strings != null && __isset.strings)
            {
                if(!__first) { sb.Append(", "); }
                __first = false;
                sb.Append("Strings: ");
                sb.Append(Strings);
            }
            if (Hello != null && __isset.hello)
            {
                if(!__first) { sb.Append(", "); }
                __first = false;
                sb.Append("Hello: ");
                sb.Append(Hello);
            }
            sb.Append(")");
            return sb.ToString();
        }
    }

}
