/**
 * Autogenerated by Thrift Compiler (@PACKAGE_VERSION@)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Threading;
using System.Threading.Tasks;
using Thrift;
using Thrift.Collections;

using Thrift.Protocols;
using Thrift.Protocols.Entities;
using Thrift.Protocols.Utilities;
using Thrift.Transports;
using Thrift.Transports.Client;
using Thrift.Transports.Server;


namespace thrift.test
{

    public partial class Xtruct : TBase
    {
        private string _string_thing;
        private sbyte _byte_thing;
        private int _i32_thing;
        private long _i64_thing;

        public string String_thing
        {
            get
            {
                return _string_thing;
            }
            set
            {
                __isset.string_thing = true;
                this._string_thing = value;
            }
        }

        public sbyte Byte_thing
        {
            get
            {
                return _byte_thing;
            }
            set
            {
                __isset.byte_thing = true;
                this._byte_thing = value;
            }
        }

        public int I32_thing
        {
            get
            {
                return _i32_thing;
            }
            set
            {
                __isset.i32_thing = true;
                this._i32_thing = value;
            }
        }

        public long I64_thing
        {
            get
            {
                return _i64_thing;
            }
            set
            {
                __isset.i64_thing = true;
                this._i64_thing = value;
            }
        }


        public Isset __isset;
        public struct Isset
        {
            public bool string_thing;
            public bool byte_thing;
            public bool i32_thing;
            public bool i64_thing;
        }

        public Xtruct()
        {
        }

        public async Task ReadAsync(TProtocol iprot, CancellationToken cancellationToken)
        {
            iprot.IncrementRecursionDepth();
            try
            {
                TField field;
                await iprot.ReadStructBeginAsync(cancellationToken);
                while (true)
                {
                    field = await iprot.ReadFieldBeginAsync(cancellationToken);
                    if (field.Type == TType.Stop)
                    {
                        break;
                    }

                    switch (field.ID)
                    {
                        case 1:
                            if (field.Type == TType.String)
                            {
                                String_thing = await iprot.ReadStringAsync(cancellationToken);
                            }
                            else
                            {
                                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
                            }
                            break;
                        case 4:
                            if (field.Type == TType.Byte)
                            {
                                Byte_thing = await iprot.ReadByteAsync(cancellationToken);
                            }
                            else
                            {
                                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
                            }
                            break;
                        case 9:
                            if (field.Type == TType.I32)
                            {
                                I32_thing = await iprot.ReadI32Async(cancellationToken);
                            }
                            else
                            {
                                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
                            }
                            break;
                        case 11:
                            if (field.Type == TType.I64)
                            {
                                I64_thing = await iprot.ReadI64Async(cancellationToken);
                            }
                            else
                            {
                                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
                            }
                            break;
                        default: 
                            await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
                            break;
                    }

                    await iprot.ReadFieldEndAsync(cancellationToken);
                }

                await iprot.ReadStructEndAsync(cancellationToken);
            }
            finally
            {
                iprot.DecrementRecursionDepth();
            }
        }

        public async Task WriteAsync(TProtocol oprot, CancellationToken cancellationToken)
        {
            oprot.IncrementRecursionDepth();
            try
            {
                var struc = new TStruct("Xtruct");
                await oprot.WriteStructBeginAsync(struc, cancellationToken);
                var field = new TField();
                if (String_thing != null && __isset.string_thing)
                {
                    field.Name = "string_thing";
                    field.Type = TType.String;
                    field.ID = 1;
                    await oprot.WriteFieldBeginAsync(field, cancellationToken);
                    await oprot.WriteStringAsync(String_thing, cancellationToken);
                    await oprot.WriteFieldEndAsync(cancellationToken);
                }
                if (__isset.byte_thing)
                {
                    field.Name = "byte_thing";
                    field.Type = TType.Byte;
                    field.ID = 4;
                    await oprot.WriteFieldBeginAsync(field, cancellationToken);
                    await oprot.WriteByteAsync(Byte_thing, cancellationToken);
                    await oprot.WriteFieldEndAsync(cancellationToken);
                }
                if (__isset.i32_thing)
                {
                    field.Name = "i32_thing";
                    field.Type = TType.I32;
                    field.ID = 9;
                    await oprot.WriteFieldBeginAsync(field, cancellationToken);
                    await oprot.WriteI32Async(I32_thing, cancellationToken);
                    await oprot.WriteFieldEndAsync(cancellationToken);
                }
                if (__isset.i64_thing)
                {
                    field.Name = "i64_thing";
                    field.Type = TType.I64;
                    field.ID = 11;
                    await oprot.WriteFieldBeginAsync(field, cancellationToken);
                    await oprot.WriteI64Async(I64_thing, cancellationToken);
                    await oprot.WriteFieldEndAsync(cancellationToken);
                }
                await oprot.WriteFieldStopAsync(cancellationToken);
                await oprot.WriteStructEndAsync(cancellationToken);
            }
            finally
            {
                oprot.DecrementRecursionDepth();
            }
        }

        public override string ToString()
        {
            var sb = new StringBuilder("Xtruct(");
            bool __first = true;
            if (String_thing != null && __isset.string_thing)
            {
                if(!__first) { sb.Append(", "); }
                __first = false;
                sb.Append("String_thing: ");
                sb.Append(String_thing);
            }
            if (__isset.byte_thing)
            {
                if(!__first) { sb.Append(", "); }
                __first = false;
                sb.Append("Byte_thing: ");
                sb.Append(Byte_thing);
            }
            if (__isset.i32_thing)
            {
                if(!__first) { sb.Append(", "); }
                __first = false;
                sb.Append("I32_thing: ");
                sb.Append(I32_thing);
            }
            if (__isset.i64_thing)
            {
                if(!__first) { sb.Append(", "); }
                __first = false;
                sb.Append("I64_thing: ");
                sb.Append(I64_thing);
            }
            sb.Append(")");
            return sb.ToString();
        }
    }

}
