/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace Thrift.Test
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class ListTypeVersioningV2 : TBase
  {
    private List<string> _strings;
    private string _hello;

    public List<string> Strings
    {
      get
      {
        return _strings;
      }
      set
      {
        __isset.strings = true;
        this._strings = value;
      }
    }

    public string Hello
    {
      get
      {
        return _hello;
      }
      set
      {
        __isset.hello = true;
        this._hello = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool strings;
      public bool hello;
    }

    public ListTypeVersioningV2() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.List) {
              {
                Strings = new List<string>();
                TList _list61 = iprot.ReadListBegin();
                for( int _i62 = 0; _i62 < _list61.Count; ++_i62)
                {
                  string _elem63;
                  _elem63 = iprot.ReadString();
                  Strings.Add(_elem63);
                }
                iprot.ReadListEnd();
              }
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 2:
            if (field.Type == TType.String) {
              Hello = iprot.ReadString();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("ListTypeVersioningV2");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (Strings != null && __isset.strings) {
        field.Name = "strings";
        field.Type = TType.List;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        {
          oprot.WriteListBegin(new TList(TType.String, Strings.Count));
          foreach (string _iter64 in Strings)
          {
            oprot.WriteString(_iter64);
          }
          oprot.WriteListEnd();
        }
        oprot.WriteFieldEnd();
      }
      if (Hello != null && __isset.hello) {
        field.Name = "hello";
        field.Type = TType.String;
        field.ID = 2;
        oprot.WriteFieldBegin(field);
        oprot.WriteString(Hello);
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder __sb = new StringBuilder("ListTypeVersioningV2(");
      bool __first = true;
      if (Strings != null && __isset.strings) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("Strings: ");
        __sb.Append(Strings);
      }
      if (Hello != null && __isset.hello) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("Hello: ");
        __sb.Append(Hello);
      }
      __sb.Append(")");
      return __sb.ToString();
    }

  }

}
