name: tutorial_console_client
version: 0.1.0
description: >
  A Dart console client to implementation of the Apache Thrift tutorial
author: Mark Erickson <mark.erickson@workiva.com>
homepage: https://github.com/apache/thrift

environment:
  sdk: ^1.12.0

dependencies:
  args: ^0.13.0
  collection: ^1.1.0
  shared:
    path: ../gen-dart/shared
  thrift:
    path: ../../../lib/dart
  tutorial:
    path: ../gen-dart/tutorial
