SOURCES = ../gen-ocaml/ThriftTest_types.ml ../gen-ocaml/ThriftTest_consts.ml ../gen-ocaml/SecondService.ml ../gen-ocaml/ThriftTest.ml TestServer.ml
RESULT = ts
INCDIRS = "/home/iproctor/code/projects/thrift/trunk/lib/ocaml/src/" "../gen-ocaml/"
LIBS = unix thrift
all: nc
OCAMLMAKEFILE = ../../../lib/ocaml/OCamlMakefile
include $(OCAMLMAKEFILE)
