#
# Autogenerated by Thrift
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#

require 'thrift/protocol'

module SpecNamespace
    class Hello
      include ::Thrift::Struct
      GREETING = 1

      Thrift::Struct.field_accessor self, :greeting
      FIELDS = {
        GREETING => {:type => Thrift::Types::STRING, :name => 'greeting', :default => %q"hello world"}
      }

      def struct_fields; FIELDS; end

      def validate
      end

    end

    class Foo
      include ::Thrift::Struct
      SIMPLE = 1
      WORDS = 2
      HELLO = 3
      INTS = 4
      COMPLEX = 5
      SHORTS = 6
      OPT_STRING = 7

      Thrift::Struct.field_accessor self, :simple, :words, :hello, :ints, :complex, :shorts, :opt_string
      FIELDS = {
        SIMPLE => {:type => Thrift::Types::I32, :name => 'simple', :default => 53},
        WORDS => {:type => Thrift::Types::STRING, :name => 'words', :default => %q"words"},
        HELLO => {:type => Thrift::Types::STRUCT, :name => 'hello', :default => Hello.new({
          %q"greeting" => %q"hello, world!",
        }), :class => SpecNamespace::Hello},
        INTS => {:type => Thrift::Types::LIST, :name => 'ints', :default => [
          1,
          2,
          2,
          3,
        ], :element => {:type => Thrift::Types::I32}},
        COMPLEX => {:type => Thrift::Types::MAP, :name => 'complex', :key => {:type => Thrift::Types::I32}, :value => {:type => Thrift::Types::MAP, :key => {:type => Thrift::Types::STRING}, :value => {:type => Thrift::Types::DOUBLE}}},
        SHORTS => {:type => Thrift::Types::SET, :name => 'shorts', :default => Set.new([          5,
          17,
          239,
        ]), :element => {:type => Thrift::Types::I16}},
        OPT_STRING => {:type => Thrift::Types::STRING, :name => 'opt_string', :optional => true}
      }

      def struct_fields; FIELDS; end

      def validate
      end

    end

    class BoolStruct
      include ::Thrift::Struct
      YESNO = 1

      Thrift::Struct.field_accessor self, :yesno
      FIELDS = {
        YESNO => {:type => Thrift::Types::BOOL, :name => 'yesno', :default => true}
      }

      def struct_fields; FIELDS; end

      def validate
      end

    end

    class SimpleList
      include ::Thrift::Struct
      BOOLS = 1
      BYTES = 2
      I16S = 3
      I32S = 4
      I64S = 5
      DOUBLES = 6
      STRINGS = 7
      MAPS = 8
      LISTS = 9
      SETS = 10
      HELLOS = 11

      Thrift::Struct.field_accessor self, :bools, :bytes, :i16s, :i32s, :i64s, :doubles, :strings, :maps, :lists, :sets, :hellos
      FIELDS = {
        BOOLS => {:type => Thrift::Types::LIST, :name => 'bools', :element => {:type => Thrift::Types::BOOL}},
        BYTES => {:type => Thrift::Types::LIST, :name => 'bytes', :element => {:type => Thrift::Types::BYTE}},
        I16S => {:type => Thrift::Types::LIST, :name => 'i16s', :element => {:type => Thrift::Types::I16}},
        I32S => {:type => Thrift::Types::LIST, :name => 'i32s', :element => {:type => Thrift::Types::I32}},
        I64S => {:type => Thrift::Types::LIST, :name => 'i64s', :element => {:type => Thrift::Types::I64}},
        DOUBLES => {:type => Thrift::Types::LIST, :name => 'doubles', :element => {:type => Thrift::Types::DOUBLE}},
        STRINGS => {:type => Thrift::Types::LIST, :name => 'strings', :element => {:type => Thrift::Types::STRING}},
        MAPS => {:type => Thrift::Types::LIST, :name => 'maps', :element => {:type => Thrift::Types::MAP, :key => {:type => Thrift::Types::I16}, :value => {:type => Thrift::Types::I16}}},
        LISTS => {:type => Thrift::Types::LIST, :name => 'lists', :element => {:type => Thrift::Types::LIST, :element => {:type => Thrift::Types::I16}}},
        SETS => {:type => Thrift::Types::LIST, :name => 'sets', :element => {:type => Thrift::Types::SET, :element => {:type => Thrift::Types::I16}}},
        HELLOS => {:type => Thrift::Types::LIST, :name => 'hellos', :element => {:type => Thrift::Types::STRUCT, :class => SpecNamespace::Hello}}
      }

      def struct_fields; FIELDS; end

      def validate
      end

    end

    class Xception < Thrift::Exception
      include ::Thrift::Struct
      MESSAGE = 1
      CODE = 2

      Thrift::Struct.field_accessor self, :message, :code
      FIELDS = {
        MESSAGE => {:type => Thrift::Types::STRING, :name => 'message'},
        CODE => {:type => Thrift::Types::I32, :name => 'code', :default => 1}
      }

      def struct_fields; FIELDS; end

      def validate
      end

    end

  end
