#
# Autogenerated by Thrift
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#

require 'thrift/protocol'
require File.dirname(__FILE__) + '/ThriftSpec_types'

  module SpecNamespace
end
