# Copyright 2009 The Go Authors. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

include $(GOROOT)/src/Make.inc

all: install

TARG=TutorialServerClient

DIRS=\

GOFILES=\
  CalculatorHandler.go\
  GoClient.go\
  GoServer.go\
  main.go

-include ../Make.deps

include $(GOROOT)/src/Make.cmd

